# default configuration
title = "Liam Rosenfeld"
baseURL = "https://liamrosenfeld.com"
summaryLength = "10"
disableKinds = ["taxonomy", "term"]

# menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Projects"
URL = "/projects/"
weight = 2

[[menu.main]]
name = "Posts"
URL = "/posts/"
weight = 3

# default parameters
[params]
home = "Home"
description = "Liam Rosenfeld's Website."

# author information
[params.author]
name = "Liam Rosenfeld"
email = "me@liamrosenfeld.com"
