# default configuration
baseURL = "https://liamrosenfeld.com"
summaryLength = "10"
title = "Liam Rosenfeld"

# menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Projects"
URL = "/projects/"
weight = 2

[[menu.main]]
name = "Posts"
URL = "/posts/"
weight = 3

# default parameters
[params]
home = "Home"
description = "Liam Rosenfeld's Website."

# author information
[params.author]
name = "Liam Rosenfeld"
email = "me@liamrosenfeld.com"

# Disable the default taxonomies
[taxonomies]
tag = ""
category = ""
